import type { Atributos } from './tipos';

/**
 * Atributos oficiales de cada control, extraídos de la tabla de atributos de
 * ISO/IEC 27002:2022 (cláusula 4.2: tipo, propiedades CIA, conceptos de ciberseguridad,
 * capacidades operativas y dominios de seguridad). Datos factuales de la norma.
 */
export const ATRIBUTOS: Record<string, Atributos> = {
  '5.1': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Governance"], dom: ["Governance_and_Ecosystem", "Resilience"]},
  '5.2': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Governance"], dom: ["Governance_and_Ecosystem", "Protection", "Resilience"]},
  '5.3': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Governance", "Identity_and_access_management"], dom: ["Governance_and_Ecosystem"]},
  '5.4': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Governance"], dom: ["Governance_and_Ecosystem"]},
  '5.5': {tipo: ["Preventive", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect", "Respond", "Recover"], cap: ["Governance"], dom: ["Defence", "Resilience"]},
  '5.6': {tipo: ["Preventive", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect", "Respond", "Recover"], cap: ["Governance"], dom: ["Defence"]},
  '5.7': {tipo: ["Preventive", "Detective", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Detect", "Respond"], cap: ["Threat_and_vulnerability_management"], dom: ["Defence", "Resilience"]},
  '5.8': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect"], cap: ["Governance"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '5.9': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Asset_management"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '5.10': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Asset_management", "Information_protection"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '5.11': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Asset_management"], dom: ["Protection"]},
  '5.12': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Information_protection"], dom: ["Protection", "Defence"]},
  '5.13': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Information_protection"], dom: ["Defence", "Protection"]},
  '5.14': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Asset_management", "Information_protection"], dom: ["Protection"]},
  '5.15': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Identity_and_access_management"], dom: ["Protection"]},
  '5.16': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Identity_and_access_management"], dom: ["Protection"]},
  '5.17': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Identity_and_access_management"], dom: ["Protection"]},
  '5.18': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Identity_and_access_management"], dom: ["Protection"]},
  '5.19': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Supplier_relationships_security"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '5.20': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Supplier_relationships_security"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '5.21': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Supplier_relationships_security"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '5.22': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Supplier_relationships_security", "Information_security_assurance"], dom: ["Governance_and_Ecosystem", "Protection", "Defence"]},
  '5.23': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Supplier_relationships_security"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '5.24': {tipo: ["Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Respond", "Recover"], cap: ["Governance", "Information_security_event_management"], dom: ["Defence"]},
  '5.25': {tipo: ["Detective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Detect", "Respond"], cap: ["Information_security_event_management"], dom: ["Defence"]},
  '5.26': {tipo: ["Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Respond", "Recover"], cap: ["Information_security_event_management"], dom: ["Defence"]},
  '5.27': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect"], cap: ["Information_security_event_management"], dom: ["Defence"]},
  '5.28': {tipo: ["Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Detect", "Respond"], cap: ["Information_security_event_management"], dom: ["Defence"]},
  '5.29': {tipo: ["Preventive", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect", "Respond"], cap: ["Continuity"], dom: ["Protection", "Resilience"]},
  '5.30': {tipo: ["Corrective"], cia: ["Availability"], ciber: ["Respond"], cap: ["Continuity"], dom: ["Resilience"]},
  '5.31': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Legal_and_compliance"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '5.32': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Legal_and_compliance"], dom: ["Governance_and_Ecosystem"]},
  '5.33': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect"], cap: ["Legal_and_compliance", "Asset_management", "Information_protection"], dom: ["Defence"]},
  '5.34': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect"], cap: ["Information_protection", "Legal_and_compliance"], dom: ["Protection"]},
  '5.35': {tipo: ["Preventive", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect"], cap: ["Information_security_assurance"], dom: ["Governance_and_Ecosystem"]},
  '5.36': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect"], cap: ["Legal_and_compliance", "Information_security_assurance"], dom: ["Governance_and_Ecosystem"]},
  '5.37': {tipo: ["Preventive", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect", "Recover"], cap: ["Asset_management", "Physical_security", "System_and_network_security", "Application_security", "Secure_configuration", "Identity_and_access_management", "Threat_and_vulnerability_management", "Continuity", "Information_security_event_management"], dom: ["Governance_and_Ecosystem", "Protection", "Defence"]},
  '6.1': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Human_resource_security"], dom: ["Governance_and_Ecosystem"]},
  '6.2': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Human_resource_security"], dom: ["Governance_and_Ecosystem"]},
  '6.3': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Human_resource_security"], dom: ["Governance_and_Ecosystem"]},
  '6.4': {tipo: ["Preventive", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect", "Respond"], cap: ["Human_resource_security"], dom: ["Governance_and_Ecosystem"]},
  '6.5': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Human_resource_security", "Asset_management"], dom: ["Governance_and_Ecosystem"]},
  '6.6': {tipo: ["Preventive"], cia: ["Confidentiality"], ciber: ["Protect"], cap: ["Human_resource_security", "Information_protection", "Supplier_relationships_security"], dom: ["Governance_and_Ecosystem"]},
  '6.7': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Asset_management", "Information_protection", "Physical_security", "System_and_network_security"], dom: ["Protection"]},
  '6.8': {tipo: ["Detective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Detect"], cap: ["Information_security_event_management"], dom: ["Defence"]},
  '7.1': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security"], dom: ["Protection"]},
  '7.2': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security", "Identity_and_access_management"], dom: ["Protection"]},
  '7.3': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security", "Asset_management"], dom: ["Protection"]},
  '7.4': {tipo: ["Preventive", "Detective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect", "Detect"], cap: ["Physical_security"], dom: ["Protection", "Defence"]},
  '7.5': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security"], dom: ["Protection"]},
  '7.6': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security"], dom: ["Protection"]},
  '7.7': {tipo: ["Preventive"], cia: ["Confidentiality"], ciber: ["Protect"], cap: ["Physical_security"], dom: ["Protection"]},
  '7.8': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security", "Asset_management"], dom: ["Protection"]},
  '7.9': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security", "Asset_management"], dom: ["Protection"]},
  '7.10': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security", "Asset_management"], dom: ["Protection"]},
  '7.11': {tipo: ["Preventive", "Detective"], cia: ["Integrity", "Availability"], ciber: ["Protect", "Detect"], cap: ["Physical_security"], dom: ["Protection"]},
  '7.12': {tipo: ["Preventive"], cia: ["Confidentiality", "Availability"], ciber: ["Protect"], cap: ["Physical_security"], dom: ["Protection"]},
  '7.13': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Physical_security", "Asset_management"], dom: ["Protection", "Resilience"]},
  '7.14': {tipo: ["Preventive"], cia: ["Confidentiality"], ciber: ["Protect"], cap: ["Physical_security", "Asset_management"], dom: ["Protection"]},
  '8.1': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Asset_management", "Information_protection"], dom: ["Protection"]},
  '8.2': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Identity_and_access_management"], dom: ["Protection"]},
  '8.3': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Identity_and_access_management"], dom: ["Protection"]},
  '8.4': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Identity_and_access_management", "Application_security", "Secure_configuration"], dom: ["Protection"]},
  '8.5': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Identity_and_access_management"], dom: ["Protection"]},
  '8.6': {tipo: ["Preventive", "Detective"], cia: ["Integrity", "Availability"], ciber: ["Identify", "Protect", "Detect"], cap: ["Continuity"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '8.7': {tipo: ["Preventive", "Detective", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect", "Detect"], cap: ["System_and_network_security", "Information_protection"], dom: ["Protection", "Defence"]},
  '8.8': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect"], cap: ["Threat_and_vulnerability_management"], dom: ["Governance_and_Ecosystem", "Protection", "Defence"]},
  '8.9': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Secure_configuration"], dom: ["Protection"]},
  '8.10': {tipo: ["Preventive"], cia: ["Confidentiality"], ciber: ["Protect"], cap: ["Information_protection", "Legal_and_compliance"], dom: ["Protection"]},
  '8.11': {tipo: ["Preventive"], cia: ["Confidentiality"], ciber: ["Protect"], cap: ["Information_protection"], dom: ["Protection"]},
  '8.12': {tipo: ["Preventive", "Detective"], cia: ["Confidentiality"], ciber: ["Protect", "Detect"], cap: ["Information_protection"], dom: ["Protection", "Defence"]},
  '8.13': {tipo: ["Corrective"], cia: ["Integrity", "Availability"], ciber: ["Recover"], cap: ["Continuity"], dom: ["Protection"]},
  '8.14': {tipo: ["Preventive"], cia: ["Availability"], ciber: ["Protect"], cap: ["Continuity", "Asset_management"], dom: ["Protection", "Resilience"]},
  '8.15': {tipo: ["Detective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Detect"], cap: ["Information_security_event_management"], dom: ["Protection", "Defence"]},
  '8.16': {tipo: ["Detective", "Corrective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Detect", "Respond"], cap: ["Information_security_event_management"], dom: ["Defence"]},
  '8.17': {tipo: ["Detective"], cia: ["Integrity"], ciber: ["Protect", "Detect"], cap: ["Information_security_event_management"], dom: ["Protection", "Defence"]},
  '8.18': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["System_and_network_security", "Secure_configuration", "Application_security"], dom: ["Protection"]},
  '8.19': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Secure_configuration", "Application_security"], dom: ["Protection"]},
  '8.20': {tipo: ["Preventive", "Detective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect", "Detect"], cap: ["System_and_network_security"], dom: ["Protection"]},
  '8.21': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["System_and_network_security"], dom: ["Protection"]},
  '8.22': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["System_and_network_security"], dom: ["Protection"]},
  '8.23': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["System_and_network_security"], dom: ["Protection"]},
  '8.24': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Secure_configuration"], dom: ["Protection"]},
  '8.25': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Application_security", "System_and_network_security"], dom: ["Protection"]},
  '8.26': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Application_security", "System_and_network_security"], dom: ["Protection", "Defence"]},
  '8.27': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Application_security", "System_and_network_security"], dom: ["Protection"]},
  '8.28': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Application_security", "System_and_network_security"], dom: ["Protection"]},
  '8.29': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify"], cap: ["Application_security", "Information_security_assurance", "System_and_network_security"], dom: ["Protection"]},
  '8.30': {tipo: ["Preventive", "Detective"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Identify", "Protect", "Detect"], cap: ["System_and_network_security", "Application_security", "Supplier_relationships_security"], dom: ["Governance_and_Ecosystem", "Protection"]},
  '8.31': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Application_security", "System_and_network_security"], dom: ["Protection"]},
  '8.32': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["Application_security", "System_and_network_security"], dom: ["Protection"]},
  '8.33': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity"], ciber: ["Protect"], cap: ["Information_protection"], dom: ["Protection"]},
  '8.34': {tipo: ["Preventive"], cia: ["Confidentiality", "Integrity", "Availability"], ciber: ["Protect"], cap: ["System_and_network_security", "Information_protection"], dom: ["Governance_and_Ecosystem", "Protection"]},
};

/**
 * Enunciado del control en el texto oficial inglés de ISO/IEC 27002:2022 (cita breve
 * con fines de referencia; el resumen operativo en español está en controles.ts).
 */
export const ENUNCIADO_EN: Record<string, string> = {
  '5.1': "Information security policy and topic-specific policies should be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.",
  '5.2': "Information security roles and responsibilities should be defined and allocated according to the organization needs. 11 ISO/IEC 27002:2022(E).",
  '5.3': "Conflicting duties and conflicting areas of responsibility should be segregated.",
  '5.4': "Management should require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization.",
  '5.5': "The organization should establish and maintain contact with relevant authorities.",
  '5.6': "The organization should establish and maintain contact with special interest groups or other specialist security forums and professional associations.",
  '5.7': "Information relating to information security threats should be collected and analysed to produce threat intelligence.",
  '5.8': "Information security should be integrated into project management.",
  '5.9': "An inventory of information and other associated assets, including owners, should be developed and maintained.",
  '5.10': "Rules for the acceptable use and procedures for handling information and other associated assets should be identified, documented and implemented.",
  '5.11': "Personnel and other interested parties as appropriate should return all the organization’s assets in their possession upon change or termination of their employment, contract or agreement.",
  '5.12': "Information should be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.",
  '5.13': "An appropriate set of procedures for information labelling should be developed and implemented in accordance with the information classification scheme adopted by the organization.",
  '5.14': "Information transfer rules, procedures, or agreements should be in place for all types of transfer facilities within the organization and between the organization and other parties. 24 ISO/IEC 27002:2022(E).",
  '5.15': "Rules to control physical and logical access to information and other associated assets should be established and implemented based on business and information security requirements.",
  '5.16': "The full life cycle of identities should be managed.",
  '5.17': "Allocation and management of authentication information should be controlled by a management process, including advising personnel on the appropriate handling of authentication information.",
  '5.18': "Access rights to information and other associated assets should be provisioned, reviewed, modified and removed in accordance with the organization’s topic-specific policy on and rules for access control.",
  '5.19': "Processes and procedures should be defined and implemented to manage the information security risks associated with the use of supplier’s products or services.",
  '5.20': "Relevant information security requirements should be established and agreed with each supplier based on the type of supplier relationship.",
  '5.21': "Processes and procedures should be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.",
  '5.22': "The organization should regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.",
  '5.23': "Processes for acquisition, use, management and exit from cloud services should be established in accordance with the organization’s information security requirements.",
  '5.24': "The organization should plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.",
  '5.25': "The organization should assess information security events and decide if they are to be categorized as information security incidents.",
  '5.26': "Information security incidents should be responded to in accordance with the documented procedures.",
  '5.27': "Knowledge gained from information security incidents should be used to strengthen and improve the information security controls.",
  '5.28': "The organization should establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.",
  '5.29': "The organization should plan how to maintain information security at an appropriate level during disruption.",
  '5.30': "ICT readiness should be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements. 48 ISO/IEC 27002:2022(E).",
  '5.31': "Legal, statutory, regulatory and contractual requirements relevant to information security and the organization’s approach to meet these requirements should be identified, documented and kept up to date.",
  '5.32': "The organization should implement appropriate procedures to protect intellectual property rights.",
  '5.33': "Records should be protected from loss, destruction, falsification, unauthorized access and unauthorized release.",
  '5.34': "The organization should identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.",
  '5.35': "The organization’s approach to managing information security and its implementation including people, processes and technologies should be reviewed independently at planned intervals, or when significant changes occur.",
  '5.36': "Compliance with the organization’s information security policy, topic-specific policies, rules and standards should be regularly reviewed.",
  '5.37': "Operating procedures for information processing facilities should be documented and made available to personnel who need them.",
  '6.1': "Background verification checks on all candidates to become personnel should be carried out prior to joining the organization and on an ongoing basis taking into consideration applicable laws, regulations and ethics and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.",
  '6.2': "The employment contractual agreements should state the personnel’s and the organization’s responsibilities for information security.",
  '6.3': "Personnel of the organization and relevant interested parties should receive appropriate information security awareness, education and training and regular updates of the organization's information security policy, topic-specific policies and procedures, as relevant for their job function.",
  '6.4': "A disciplinary process should be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.",
  '6.5': "Information security responsibilities and duties that remain valid after termination or change of employment should be defined, enforced and communicated to relevant personnel and other interested parties.",
  '6.6': "Confidentiality or non-disclosure agreements reflecting the organization’s needs for the protection of information should be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.",
  '6.7': "Security measures should be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization’s premises.",
  '6.8': "The organization should provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.",
  '7.1': "Security perimeters should be defined and used to protect areas that contain information and other associated assets.",
  '7.2': "Secure areas should be protected by appropriate entry controls and access points.",
  '7.3': "Physical security for offices, rooms and facilities should be designed and implemented.",
  '7.4': "Premises should be continuously monitored for unauthorized physical access.",
  '7.5': "Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure should be designed and implemented. 71 ISO/IEC 27002:2022(E).",
  '7.6': "Security measures for working in secure areas should be designed and implemented. 72 ISO/IEC 27002:2022(E).",
  '7.7': "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities should be defined and appropriately enforced.",
  '7.8': "Equipment should be sited securely and protected.",
  '7.9': "Off-site assets should be protected.",
  '7.10': "Storage media should be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organization’s classification scheme and handling requirements.",
  '7.11': "Information processing facilities should be protected from power failures and other disruptions caused by failures in supporting utilities.",
  '7.12': "Cables carrying power, data or supporting information services should be protected from interception, interference or damage.",
  '7.13': "Equipment should be maintained correctly to ensure availability, integrity and confidentiality of information.",
  '7.14': "Items of equipment containing storage media should be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.",
  '8.1': "Information stored on, processed by or accessible via user endpoint devices should be protected.",
  '8.2': "The allocation and use of privileged access rights should be restricted and managed.",
  '8.3': "Access to information and other associated assets should be restricted in accordance with the established topic-specific policy on access control.",
  '8.4': "Read and write access to source code, development tools and software libraries should be appropriately managed.",
  '8.5': "Secure authentication technologies and procedures should be implemented based on information access restrictions and the topic-specific policy on access control.",
  '8.6': "The use of resources should be monitored and adjusted in line with current and expected capacity requirements.",
  '8.7': "Protection against malware should be implemented and supported by appropriate user awareness.",
  '8.8': "Information about technical vulnerabilities of information systems in use should be obtained, the organization’s exposure to such vulnerabilities should be evaluated and appropriate measures should be taken.",
  '8.9': "Configurations, including security configurations, of hardware, software, services and networks should be established, documented, implemented, monitored and reviewed.",
  '8.10': "Information stored in information systems, devices or in any other storage media should be deleted when no longer required.",
  '8.11': "Data masking should be used in accordance with the organization’s topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.",
  '8.12': "Data leakage prevention measures should be applied to systems, networks and any other devices that process, store or transmit sensitive information.",
  '8.13': "Backup copies of information, software and systems should be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.",
  '8.14': "Information processing facilities should be implemented with redundancy sufficient to meet availability requirements.",
  '8.15': "Logs that record activities, exceptions, faults and other relevant events should be produced, stored, protected and analysed. 103 ISO/IEC 27002:2022(E).",
  '8.16': "Networks, systems and applications should be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.",
  '8.17': "The clocks of information processing systems used by the organization should be synchronized to approved time sources.",
  '8.18': "The use of utility programs that can be capable of overriding system and application controls should be restricted and tightly controlled.",
  '8.19': "Procedures and measures should be implemented to securely manage software installation on operational systems.",
  '8.20': "Networks and network devices should be secured, managed and controlled to protect information in systems and applications.",
  '8.21': "Security mechanisms, service levels and service requirements of network services should be identified, implemented and monitored.",
  '8.22': "Groups of information services, users and information systems should be segregated in the organization’s networks.",
  '8.23': "Access to external websites should be managed to reduce exposure to malicious content.",
  '8.24': "Rules for the effective use of cryptography, including cryptographic key management, should be defined and implemented.",
  '8.25': "Rules for the secure development of software and systems should be established and applied.",
  '8.26': "Information security requirements should be identified, specified and approved when developing or acquiring applications.",
  '8.27': "Principles for engineering secure systems should be established, documented, maintained and applied to any information system development activities.",
  '8.28': "Secure coding principles should be applied to software development.",
  '8.29': "Security testing processes should be defined and implemented in the development life cycle. 124 ISO/IEC 27002:2022(E).",
  '8.30': "The organization should direct, monitor and review the activities related to outsourced system development.",
  '8.31': "Development, testing and production environments should be separated and secured.",
  '8.32': "Changes to information processing facilities and information systems should be subject to change management procedures.",
  '8.33': "Test information should be appropriately selected, protected and managed.",
  '8.34': "Audit tests and other assurance activities involving assessment of operational systems should be planned and agreed between the tester and appropriate management.",
};
